services:
  linkstack:
    image: linkstackorg/linkstack:latest
    container_name: linkstack
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:443
    volumes:
      - /etc/timezone:/etc/timezone
      - linkstack:/htdocs
    environment:
      - SERVER_ADMIN=${EMAIL}
      - HTTPS_SERVER_NAME=${HTTPS_SERVER_NAME}
      - LOG_LEVEL=info
      - PHP_MEMORY_LIMIT=512M
      - UPLOAD_MAX_FILESIZE=16M

volumes:
  linkstack:
