services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    restart: unless-stopped
    ports:
      - ${NTFY_PORT}:80
    volumes:
      - /etc/timezone:/etc/timezone
      - ${NTFY_DIR}/var/cache/ntfy:/var/cache/ntfy
      - ${NTFY_DIR}/etc/ntfy:/etc/ntfy
    command:
      - serve
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://10.27.1.60:1111/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
