services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - ${WEB_PORT}:9000
    volumes:
      - /etc/timezone:/etc/timezone
      - ${DATA_DIR}:/data
      - ${DOCKER_VOLUMES}
      - ${SECRET_DIR}
