services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - ${KUMA_PORT}:3001
    volumes:
      - /etc/timezone:/etc/timezone
      - ${KUMA_DIR}:/app/data
      - ${SECRET_DIR}
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=true