services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - ${WEB_PORT}:81 # Admin Panel
    volumes:
      - /etc/timezone:/etc/timezone
      - ${DATA_DIR}:/data
      - ${LETSENCRYPT_DIR}:/etc/letsencrypt